name: common
on:
  workflow_call:
    inputs:
      Project:
        description: "Enter your project name"
        required: true
        type: string
      Application:
        description: "Enter your App name"
        required: true
        type: string
      app_type:
        description: "Enter your app type"
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: display files
        run: ls -l 

      - name: read ${{ inputs.app_type }} version 
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: print app version
        run: echo "print version ${{ env.VERSION }}"

      - name: Install dependencies
        run: npm install 

      - name: Docker build 
        run: docker build -t 799345568171.dkr.ecr.us-east-1.amazonaws.com/catalogue:${{ env.VERSION }} .

      - name: Configure AWS Credentials 2
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ inputs.secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.secrets.aws-secret-access-key }}

      - name: push docker image 
        run: docker push 799345568171.dkr.ecr.us-east-1.amazonaws.com/catalogue:${{ env.VERSION }}