name: common
on:
  workflow_call:
    inputs:
      Project:
        description: "Enter your project name"
        required: true
        type: string
      Application:
        description: "Enter your App name"
        required: true
        type: string
      app_type:
        description: "Enter your app type"
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  ci:
    runs-on: self-hosted
    outputs:
      appVersion: ${{ steps.package-version.outputs.VERSION }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: display files
        run: ls -l 

      - name: read ${{ inputs.app_type }} version 
        id: package-version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: print app version
        run: echo "print version ${{ steps.package-version.outputs.VERSION }}"

      - name: Install dependencies
        run: npm install 

      - name: Docker build 
        run: docker build -t 799345568171.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.Project }}/${{ inputs.Application }}:${{ steps.package-version.outputs.VERSION }} .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

      - name: push docker image 
        run: | 
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 799345568171.dkr.ecr.us-east-1.amazonaws.com
          docker push 799345568171.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.Project }}/${{ inputs.Application }}:${{ steps.package-version.outputs.VERSION }}

  cd:
    runs-on: self-hosted
    needs: ci
    env: 
      appVersion: ${{ needs.ci.outputs.appVersion }}
    steps:
      - name: checkout catalogue-deploy repo
        uses: actions/checkout@v4
        with:
          repository: DevSecOps-actions/catalogue-deploy

      - name: List files
        run: ls -la
        
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

      - name: Authenticate to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name roboshop-dev
          kubectl get nodes

      - name: deploy ${{ inputs.Application }}
        run: helm upgrade --install ${{ inputs.Application }} -f values.yaml --set deployment.imageVersion=${{ env.appVersion }} .